services:
  web:
    build: .
    container_name: tib_saas_app
    restart: always
    ports:
      - "8001:8000" # Expose on 8001 to avoid conflict with existing site
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/tib_saas.db
    # networks: # Network not needed if strictly local proxy
    #   - web_gateway

volumes:
  data:


